import "@/styles/globals.css";
import { type Locale, i18n } from "@/i18n-config";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Nunito, Vazirmatn } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"], variable: "--nunito-font" });
const vazirmatn = Vazirmatn({ subsets: ["arabic"], variable: "--vazirmatn-font" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

interface IRootLayout {
  children: ReactNode;
  params: { lang: Locale };
}
export default function RootLayout({ children, params: { lang } }: IRootLayout) {
  return (
    <html
      lang={lang}
      dir={lang === "en" ? "ltr" : "rtl"}
      className={`${vazirmatn.variable} ${nunito.variable}`}>
      <body>{children}</body>
    </html>
  );
}
